services:
  db:
    image: postgres:17.2-alpine3.21
    restart: always
    env_file:
      .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${PORT_DB}:${PORT_DB}"